name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ruigpb
          snake_svg: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg

      - name: Commit and Push Snake Animation
        run: |
          mkdir -p .github/assets
          cp dist/snake.svg .github/assets/snake.svg
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .github/assets/snake.svg
          git commit -m "Update snake animation" || echo "No changes"
          git push
